#!/bin/sh

url="https://my-cpp-app-dev-my-cpp-app-dev.apps.cluster-9xl8s.9xl8s.sandbox2979.opentlc.com"

while true; do
  response=$(curl -s "$url")
  if [ $? -eq 0 ]; then 
    echo "API call successful!"
    echo "Response: $response" 
  else
    echo "Error: Failed to reach API. Retrying in 1 second..."
  fi
  sleep 1
done

